  ##📄 docker-compose.yml

  version: '3.8'

  services:
    db:
      image: mysql:8.0
      container_name: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: livin
        MYSQL_USER: livinuser
        MYSQL_PASSWORD: livinpass
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql

    redis:
      image: redis:7.2
      container_name: redis
      restart: always
      ports:
        - "6379:6379"

    backend:
      image: livinorg/livin-be:latest # ← 실제 Docker Hub 이미지 이름으로 변경
      container_name: livin-be
      depends_on:
        - db
        - redis
      restart: always
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/livin
        SPRING_DATASOURCE_USERNAME: livinuser
        SPRING_DATASOURCE_PASSWORD: livinpass
        SPRING_REDIS_HOST: redis
        SPRING_REDIS_PORT: 6379
        TZ: Asia/Seoul

  volumes:
    db-data: